<?php
echo $this->form()->openTag($form);
?>
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<h3><?php echo $this->title; ?></h3>
			
			<!-- Hidden Elements -->
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
				<?php echo $this->formRow($form->get('UUID')); ?>
				<?php echo $this->formRow($form->get('DATE_CREATED')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('POLE_NUMBER')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('HOUSE_NUMBER')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('STREET')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('INTERSECTING_STREET')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('ACTION')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('DESCRIPTION')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('PHONE_NUMBER')); ?>
			</div>
			<div class="form-group">
				<?php // echo $this->formRow($form->get('DATE_MODIFIED')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag($form); ?>